### ISSUE TITLE
Incompatibility with stackblitz

### ISSUE THREAD

**Issue by pi0** [brc-dd/iron-webcrypto#13]
Hi

Moving the report from https://github.com/unjs/h3/issues/337 to here to track and share with the stackblitz team since it is closer to the source.

Basically, this package is broken on [Stackblitz.com](https://stackblitz.com/) due to crypto incompatibilities with `subtle.importKey` not being supported (there might be more issues once this is fixed)

Reproduction: https://stackblitz.com/edit/stackblitz-starters-coskra

(you can use `node h3.mjs`, `node crypto.mjs` and `node iron-webcrypto.mjs` for reproductions)

**Comment by brc-dd** [comment]
I don't think it will work properly even after that. Almost whole webcrypto implementation is non-standard on stackblitz -- https://stackblitz.com/edit/node-opczp3?file=index.js,with-polyfill.js,out.log

Also, even the polyfill doesn't work properly for all cases (missing node APIs?). But should work with the default options 👀

**Comment by pi0** [comment]
Hi @brc-dd. FYI, stackblitz team almost prepared the missing crypto utils to get iron-webcrypto working out of the box 🚀

**Comment by brc-dd** [comment]
Original example seems to work fine now 🚀
