### ISSUE TITLE
default iterations for pbkdf2 is 1

### ISSUE THREAD

**Issue by meesvandongen** [brc-dd/iron-webcrypto#15]
The default iteration count is 1, while the spec recommends something different; https://datatracker.ietf.org/doc/html/rfc2898#section-4.2

>  An iteration count has traditionally served the purpose of increasing the cost of producing keys from a password, thereby also increasing the difficulty of attack. For the methods in this document, a minimum of 1000 iterations is recommended. This will increase the cost of exhaustive search for passwords significantly, without a noticeable impact in the cost of deriving individual keys 

I am no expert in cryptography by any means, so I have no idea if this is even problematic. Is there any reason the default is set to 1 in this case? 

I suppose it is not possible to change the default because decryption will not work anymore for existing sessions that have a different iteration count; but perhaps in a v2 this could be changed.

**Comment by brc-dd** [comment]
Ah, the current recommendation for PBKDF2-HMAC-SHA256 (default in Iron) is 600,000 (https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html)

It was updated in the original library - https://github.com/hapijs/iron/pull/20

But was later reverted. Refer this comment by Eran - https://github.com/hapijs/iron/commit/3713143bbbee5d09aea86dfd9575ddcfb006196c#r7688885
