### ISSUE TITLE
Buffer is not tree-shakable

### ISSUE THREAD

**Issue by pi0** [brc-dd/iron-webcrypto#2]
Hi dear @brc-dd. Recently we have added session support to [h3](https://github.com/unjs/h3) which exposes it to all Nitro and Nuxt 3 users as well.

A post-release issue I have discovered is that fixture sizes significantly increased https://github.com/nuxt/nuxt/actions/runs/4108883436/jobs/7090085836 for server bundle size. Investigating more, i have found that it is becaue of `buffer` polyfill added from the entrypoint. 

For context, Nuxt and Nitro already polyfill `Buffer` for nodeless environments using [unenv](https://github.com/unjs/unenv) framework so this is not needed.

I am wondering is it possible if you can expose a subpath without Buffer polyfill? 🙏🏼 (another nice alternative, would be supporting export conditions to avoid doing this for node conditions at least)

**Comment by pi0** [comment]
Update: As a temporary workaround, inlining iron-webcrypto into h3 coude.

**Comment by brc-dd** [comment]
Hey, can you try if v0.3.0 works. It doesn't seem to work locally for me.

**Comment by pi0** [comment]
Thanks for the updates. Much nicer with unit/base64 👍🏼

**Comment by pi0** [comment]
(BTW checking the previous build, it seems was okay. node condition happens for files inside `server/` directory using icon-webcrypto)

**Comment by brc-dd** [comment]
Ah, actually I had not run cleanup 😅
